name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # รันทุกเที่ยงคืน
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # 1. บอทเจนรูปงู
      - uses: Platane/snk@v3
        with:
          github_user_name: mok-68
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?color_snake=#7928CA&color_dots=#EBEDF0,#9BE9A8,#40C463,#30A14E,#216E39
            
      # 2. ใช้บอทตัวนี้แทน ดันไฟล์เข้า branch output ง่ายกว่าเยอะ!
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
